#!/usr/bin/env bash
#Script tha modifies a source file
cp /etc/hosts /etc/hosts.old
cp /etc/hosts /etc/hosts.tmp
sed -i 's/127\.0\.0\.1/127\.0\.0\.2/' /etc/hosts.tmp
echo >> /etc/hosts.tmp
echo -e '8.8.8.8\tfacebook.com' >> /etc/hosts.tmp
cat /etc/hosts.tmp > /etc/hosts
rm /etc/hosts.tmp
